// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package auth

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"github.com/TimRobillard/handicap_tracker/views/layout"
)

func Register() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<main><div class=\"w-full md:max-w-7xl mx-auto p-2 md:p-8 flex flex-col items-center gap-10\"><div class=\"flex flex-row items-center py-4 px-2 w-full\"><a href=\"/\" class=\"text-black font-semibold text-sm hover:text-slate-700 transition-colors\">Golf IndX</a></div><form hx-ext=\"loading-states, response-targets\" hx-post=\"/auth/register\" hx-target-401=\"#register-errors\" class=\"flex flex-col w-full md:w-5/12 gap-4 mt-12\"><div class=\"mb-6\"><h3 class=\"font-semibold text-2xl text-center\">Create an account</h3><h3 class=\"text-center text-slate-600\">Enter your email to sign up for Golf IndX</h3></div><input id=\"username\" autofocus class=\"border h-auto rounded-md flex-auto p-2 focus-within:outline-green-800\" type=\"text\" name=\"username\" value=\"\" placeholder=\"username\"> <input class=\"border h-auto rounded-md flex-auto p-2 focus-within:outline-green-800\" id=\"password\" type=\"password\" name=\"password\" value=\"\" placeholder=\"password\"><div id=\"register-errors\"></div><button type=\"submit\" class=\"px-4 py-2 bg-green-800 text-white rounded-md sm:w-full hover:bg-opacity-70 transition-all focus-within:bg-opacity-70 focus-within:outline-green-800\" data-loading-class=\"opacity-80\" data-loading-disable><span data-loading-class=\"hidden\">Sign up with email</span> <span data-loading>Loading</span></button></form><div><p>Have an account?</p><p><a href=\"/login\" class=\"text-green-800\">Login</a> instead!</p></div><hr class=\"w-full md:w-5/12\"><div class=\"md:w-5/12 px-6\"><p class=\"text-slate-600\">By clicking continue, you agree to our <a href=\"/terms-of-service\" class=\"font-semibold\">Terms of Service</a> and <a href=\"/terms-of-service\" class=\"font-semibold\">Privacy Policy</a></p></div></div><div class=\"hidden opacity-80\">generate tailwind classed</div></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layouts.Base("Register | Golf IndX").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
